pipelines:
  - name: start
    pipeline:
      - sequence:
        - service: muto_compose
          plugin: ComposePlugin
          name: compose_step
        - service: muto_native
          plugin: NativePlugin
          name: native_step
          condition: "should_run_native == True"
        - service: muto_start_stack
          plugin: LaunchPlugin
          name: start_stack_step
          condition: "compose_step.success == True"
    compensation:
      - service: muto_kill_stack
        plugin: LaunchPlugin
  - name: kill
    pipeline:
      - sequence:
        - service: muto_compose
          plugin: ComposePlugin
          name: compose_step
        - service: muto_kill_stack
          plugin: LaunchPlugin
          name: kill_stack_step
          condition: "should_run_launch == True"
    compensation:
      - service: muto_kill_stack
        plugin: LaunchPlugin 
  - name: apply
    pipeline:
      - sequence:
        - service: muto_compose
          plugin: ComposePlugin
          name: compose_step
        - service: muto_apply_stack
          plugin: LaunchPlugin
          name: apply_stack_step
          condition: "compose_step.success == True"
    compensation:
      - service: muto_kill_stack
        plugin: LaunchPlugin
