#
#  Copyright (c) 2025 Composiv.ai, Eteration A.S. and others
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# and Eclipse Distribution License v1.0 which accompany this distribution.
#
# The Eclipse Public License is available at
#    http://www.eclipse.org/legal/epl-v10.html
# and the Eclipse Distribution License is available at
#   http://www.eclipse.org/org/documents/edl-v10.php.
#
# Contributors:
#    Composiv.ai, Eteration A.S. - initial API and implementation
#

pipelines:
  - name: start
    pipeline:
      - sequence:
        - service: muto_compose
          plugin: ComposePlugin
          name: compose_step
        - service: muto_native
          plugin: NativePlugin
          name: native_step
          condition: "should_run_native == True"
        - service: muto_start_stack
          plugin: LaunchPlugin
          name: start_stack_step
          condition: "compose_step.success == True"
    compensation:
      - service: muto_kill_stack
        plugin: LaunchPlugin
  - name: kill
    pipeline:
      - sequence:
        - service: muto_compose
          plugin: ComposePlugin
          name: compose_step
        - service: muto_kill_stack
          plugin: LaunchPlugin
          name: kill_stack_step
          condition: "should_run_launch == True"
    compensation:
      - service: muto_kill_stack
        plugin: LaunchPlugin 
  - name: apply
    pipeline:
      - sequence:
        - service: muto_compose
          plugin: ComposePlugin
          name: compose_step
        - service: muto_apply_stack
          plugin: LaunchPlugin
          name: apply_stack_step
          condition: "compose_step.success == True"
    compensation:
      - service: muto_kill_stack
        plugin: LaunchPlugin
